package com.example.elimauto.DTO;

import lombok.Data;

@Data
public class SpecificationsDTO {
    private String complectationId;
    private String backBrake;
    private String feeding;
    private String horsePower;
    private String kvtPower;
    private String rpmPower;
    private String engineType;
    private String transmission;
    private String drive;
    private String volume;
    private String timeToHundred;
    private String cylindersOrder;
    private String maxSpeed;
    private String compression;
    private String cylindersValue;
    private String diameter;
    private String pistonStroke;
    private String engineFeeding;
    private String engineOrder;
    private String gearValue;
    private String moment;
    private String petrolType;
    private String valves;
    private String weight;
    private String wheelSize;
    private String wheelBase;
    private String frontWheelBase;
    private String backWheelBase;
    private String frontBrake;
    private String frontSuspension;
    private String backSuspension;
    private String height;
    private String width;
    private String fuelTankCapacity;
    private String seats;
    private String length;
    private String emissionEuroClass;
    private String volumeLitres;
    private String consumptionMixed;
    private String clearance;
    private String trunksMinCapacity;
    private String trunksMaxCapacity;
    private String consumptionHighway;
    private String consumptionCity;
    private String momentRpm;
    private String fullWeight;
    private String rangeDistance;
    private String batteryCapacity;
    private String fuelEmission;
    private String electricRange;
    private String chargeTime;
    private String safetyRating;
    private String safetyGrade;
}
